config/routes.rb
Rails.application.routes.draw do


get 'sessions/new'
delete 'orders/:order_id/remove/:id', to: 'orders#remove', as: 'remove_item'
root 'products#index'

get 'login' => 'sessions#new'
post 'sessions' => 'sessions#create'
delete 'logout' => 'sessions#destroy'

patch 'users/:user_id/orders/:order_id/select/:id' => 'orders#select_card', as: 'select_card'
delete 'users/:user_id/orders/:order_id/delete/:id' => 'orders#remove_card', as: 'remove_card'
post 'users/:user_id/orders/ship/:id' => 'orders#shipped', as: 'shipped_order'


  resources :users, except: [:index, :new] do
      resources :orders, :cards, except: [:index]
  end

  resources :products, only: [:index, :show]

  
end

app/models/user.rb
class User < ActiveRecord::Base
	validates_presence_of :email
	validates :email, uniqueness: true
	
	has_many :orders
	has_many :cards
	has_many :products, through: :products_orders

	 def lastfour(number)
  	number.to_s.length <= 4 ? number : number.to_s.slice(-4..-1)
  end

  def mask(number)
  	"XXXX-XXXX-XXXX-#{lastfour(number)}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.create(user_params)
  	if @user
  		flash[:notice] = "New user created."
      session[:user_id] = @user.id
  		redirect_to products_path
  	else
  		flash[:alert] = "There was a problem, please try again."
  		redirect_to new_user_path
  	end
  end

  def edit
  end

  def update
  	if @user.update(user_params)
  		flash[:notice] = "New user updated."
  		redirect_to @user
  	else
  		flash[:alert] = "There was a problem, please try again."
  		redirect_to users_path(@user)
  	end

  end

  def destroy
  	if @user.delete
  		flash[:notice] = "User delelete"
  		redirect_to users_path
  	else 
  		flash[:alert] = "There was a problem"
  		redirect_to users_path
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:fname, :lname, :email, :address, :password)
  end

  def set_user
  	@user = User.find(params[:id])
  end



end

app/helpers/users_helper.rb
module UsersHelper
	def current_user
		session[:user_id].nil? ? nil : User.find(session[:user_id])
	end
end

app/views/users/edit.html.erb
<div id="edit">
<h1>Edit Account Information</h1>
<%= form_for(@user) do |f| %>
	<%= f.label :first_name %>
	<%= f.text_field :fname %> <br>
	<%= f.label :last_name %>
	<%= f.text_field :lname %> <br>
	<%= f.label :email %>
	<%= f.text_field :email %> <br>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<h3>Add Shipping Address:</h3>
	<%= f.label :address %>
	<%= f.text_area :address %> <br>

	<%= f.submit :update %>


<% end %>
<br>
<hr>
<%= link_to "Back", :back %>
</div>

app/views/users/index.html.erb
You can do all the shopping you want here!

app/views/users/new.html.erb
<h1>Get an account here!</h1>
<%= form_for(@user) do |f| %>
	<%= f.label :first_name %>
	<%= f.text_field :fname %> <br>
	<%= f.label :last_name %>
	<%= f.text_field :lname %> <br>
	<%= f.label :email %>
	<%= f.text_field :email %> <br>
	<%= f.label :address %>
	<%= f.text_area :address %> <br>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<%= f.submit :create %>


<% end %>
<br>
<%= link_to "Back", :back %>

app/views/users/show.html.erb
<div id="users"></div>
<h1>Welcome to your Account:</h1>
<%= @user.fname %>
<%= @user.lname %> <br>
<%= @user.email %> <br>
<%= @user.address %>
<br>
<p> <%= link_to "Edit Info", edit_user_path(@user) %></p>
<br><br>

<h2>Credit Card Information</h2>
<%= link_to "Add a Card", new_user_card_path(@user) %> <br>


<br>

<div id="cards">
<h3>Cards Already on File:</h3>
<ul>
	<% @user.cards.each do |card| %>
	<li><%= link_to "#{card.nickname}", user_card_path(user_id: @user.id, id: card.id)  %></li>
	<% end %>
</ul>
</div>
<br>
<hr>
</div>


<span id="cont">
<%= link_to "Continue Shopping", '/products' %></span>