config/routes.rb
Rails.application.routes.draw do


get 'sessions/new'
delete 'orders/:order_id/remove/:id', to: 'orders#remove', as: 'remove_item'
root 'products#index'

get 'login' => 'sessions#new'
post 'sessions' => 'sessions#create'
delete 'logout' => 'sessions#destroy'

patch 'users/:user_id/orders/:order_id/select/:id' => 'orders#select_card', as: 'select_card'
delete 'users/:user_id/orders/:order_id/delete/:id' => 'orders#remove_card', as: 'remove_card'
post 'users/:user_id/orders/ship/:id' => 'orders#shipped', as: 'shipped_order'


  resources :users, except: [:index, :new] do
      resources :orders, :cards, except: [:index]
  end

  resources :products, only: [:index, :show]

  
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :card
  has_many :orders_products
  has_many :products, through: :orders_products

	

  

def subtotals
  self.orders_products.map {|i| i.subtotal}
end
 
def total
  subtotals.sum
end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
before_action :set_user, only: [:new, :create, :show, :edit, :update, :shipped]
before_action :set_order, only: [:show, :edit, :update, :detroy]

  def index
  end

  def new
  	@order = Order.new	
  end

  def create 
     product = Product.find(params[:product_id]) 
     quantity = params[:quantity]

     if @user.orders.present? && @user.orders.last.shipped.blank?
        @order = @user.orders.last
     else
	  	  @order = Order.new
        @order.user = @user
        @order.save
     end
     item = OrdersProduct.new(order_id: @order.id, product_id: product.id, quantity: quantity)
     if item.save
	  	  flash[:notice] = "New order made."
	  	   redirect_to user_order_path(@user, @order)
	  	else
	  		flash[:alert] = "There was a problem, please try again."
	  		redirect_to new_user_order_path(user_id: params[:user_id])
	  	end
	  end

  def remove
    @op = OrdersProduct.find(params[:id])
     @op.delete
    redirect_to user_order_path(session[:user_id], params[:order_id]), notice: 'Item removed'
 
  end

  def show
  end

  def edit
  end

  def select_card
    @order = Order.find(params[:order_id])
    if @order.update(card_id: params[:id])
      redirect_to user_order_path(session[:user_id], params[:order_id]), notice: 'Card added'
    else
      redirect_to user_order_path(session[:user_id], params[:order_id]), notice: 'Something went wrong :('
    end
  end

  def remove_card
  @order = Order.find(params[:order_id])
  @order.card = nil
  if @order.save
      redirect_to user_order_path(session[:user_id], params[:order_id]), notice: 'Card added'
  else
    redirect_to user_order_path(session[:user_id], params[:order_id]), notice: 'Something went wrong :('
  end
  
  end 


   def update 
   @op = OrdersProduct.find(params[:orders_products])
     if @op.update(quantity: params[:quantity])
        flash[:notice] = "Order updated."
         redirect_to user_order_path(@user, @order)
      else
        flash[:alert] = "There was a problem, please try again."
        redirect_to user_order_path(@user, @order)
      end
   end

   def shipped
   @order = Order.find(params[:id])
   @order.shipped = true
    if @order.save
      flash[:notice] = "Order sent"
      redirect_to user_path(@user)
    else 
      flash[:alert] = "There was a problem"
      redirect_to user_path(@user)
   end
 end

private
   def order_params
  	params.require(:order).permit(:shipped)
  end

  def set_user
  	 @user = User.find(session[:user_id])
  end

  def set_order
    @order = Order.find(params[:id])
  end

  def subtotal
    @order
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
	def current_order
		current_user.orders.any? ? user_order_path(current_user.id, current_user.orders.last.id) : nil
	end
end

app/views/orders/show.html.erb
<div id="shopping">
<h1>MY SHOPPING CART</h1>
<div id="display">
<ul>
<% if @order.products.any? %>
	<% @order.orders_products.each do |op| %>
		<li>(<%= link_to "Delete", remove_item_path(@order, op), method: "delete" %>) | <%= op.product.name %>, at
	<%= number_to_currency(op.product.price,:unit => "$") %>&nbsp
		<%= form_tag(user_order_path(@user, @order), method: :patch, :style => "display:inline;" ) do %>
			<%= text_field_tag :quantity, op.quantity %>
			<%= hidden_field_tag :orders_products, op.id %>
			<%= button_tag :Update %>
		<% end %> &nbsp&nbsp
		<p>Total:</p>
		<%= number_to_currency(op.subtotal, :unit => "$")  %>

		</li> <br>

	
	<% end %>
<% else %>
	<li>No products yet :(</li>
<% end %>
</ul>
</div>
</div>
<div id="checkout">
	<h2><u>TOTAL COST OF THE ORDER:</u></h2>
	<h2><%= number_to_currency(@order.total, :unit => "$") %></h2>

	<% unless @order.card %>
	<h3>CLICK HERE TO SELECT WHICH CARD TO USE</h3>
	<ul>
	<% @user.cards.each do |card| %>
	<li><%= link_to card.nickname, select_card_path(@user, @order, card), method: :patch %></li>
	<% end %>
	<% else %>
	<h3>Using this card:</h3>
	<p><%= @order.card.nickname %> 
	<p>(<%= link_to "Click here to change your card selection.", remove_card_path(@user, @order, @order.card), method: "delete" %>)</p>
	<% end %>
</ul>
	<h3>CLICK HERE TO BUY</h3>
	<br>
	<%= button_to :Buy, shipped_order_path(@user, @order) %>

</div>
<hr>
<%= link_to "Back to your account",  user_path(@user) %>