config/routes.rb
Rails.application.routes.draw do


get 'sessions/new'
delete 'orders/:order_id/remove/:id', to: 'orders#remove', as: 'remove_item'
root 'products#index'

get 'login' => 'sessions#new'
post 'sessions' => 'sessions#create'
delete 'logout' => 'sessions#destroy'

patch 'users/:user_id/orders/:order_id/select/:id' => 'orders#select_card', as: 'select_card'
delete 'users/:user_id/orders/:order_id/delete/:id' => 'orders#remove_card', as: 'remove_card'
post 'users/:user_id/orders/ship/:id' => 'orders#shipped', as: 'shipped_order'


  resources :users, except: [:index, :new] do
      resources :orders, :cards, except: [:index]
  end

  resources :products, only: [:index, :show]

  
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :orders_products
	has_many :orders, through: :orders_products

	def previous
	  Product.find_by_id(id - 1)
	end

	def next
	  Product.find_by_id(id + 1)
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
     @productall = Product.all
    
  end

  def new
  	@product = Product.new
  end

 def create
  	@product = Product.create(product_params)

    redirect_to products_path
  end


  def show	
  	@product = Product.find(params[:id])
    @order = Order.new
  end



  def edit
      @product = Product.find(params[:id])
  end


  def update
     @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "New user updated."
      redirect_to @product
    else
      flash[:alert] = "There was a problem, please try again."
      redirect_to products_path(@product)
    end

  end


  private
  def product_params
  	params.require(:product).permit(:name, :description, :price, :photo)
  end


end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<h1>Products#new</h1>

<%= form_for(@product) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %> <br>
	<%= f.label :description %>
	<%= f.text_field :description%> <br>
	<%= f.label :price %>
	<%= f.text_field :price %> <br>
	<%= f.label :url %>
	<%= f.text_field :photo %> <br>
	
	<%= f.submit :create %>


<% end %>
<br>
<%= link_to "Back", :back %>

app/views/products/index.html.erb
<h1>WELCOME TO FURNITURE FOR LESS</h1>
<div id="allproducts">
	<h2> Items for sale...</h2>
	<% @productall.each do |product| %>
	<li><%= link_to product_path(product) do %> 
			<%= product.name %>
			<br>
			<%= image_tag product.photo %> 
     	<% end %>
	</li>
	<% end %>
</div>

<br>
<hr>



<%= link_to "Back", :back %>

app/views/products/new.html.erb
<h1>Products#new</h1>

<%= form_for(@product) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %> <br>
	<%= f.label :description %>
	<%= f.text_field :description%> <br>
	<%= f.label :price %>
	<%= f.text_field :price %> <br>
	<%= f.label :url %>
	<%= f.text_field :photo %> <br>
	
	<%= f.submit :create %>


<% end %>
<br>
<%= link_to "Back", :back %>

app/views/products/show.html.erb
<div id="product">
<div id="item">
<h1><%= @product.name %></h1>

<br>
<%= @product.description %>
<br>


<img src="<%= @product.photo %>" alt="">
<br>
<%= number_to_currency(@product.price, :unit => "$") %>
<br>
</div>
<br>
<div id="purchase">
<%= form_tag user_orders_path current_user do %>
    <%= select_tag(:quantity, options_for_select([['', nil],['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5], ['6', 6], ['7', 7], ['8', 8]])) %>
	 <input type="hidden" name="product_id" value="<%= @product.id %>">
	<br>
	<%= submit_tag "Add to Order" %>
<% end %>
<br>
</div>
<hr>
<br>

<%= link_to "Back to Main Shopping", '/products' %>
<br>
<br>
<span class="prev"><%= link_to("< Previous", @product.previous) if @product.previous %></span>
<span class="next"><%= link_to("Next >", @product.next) if @product.next %></span> 
</div>    

   