config/routes.rb
Rails.application.routes.draw do


get 'sessions/new'
delete 'orders/:order_id/remove/:id', to: 'orders#remove', as: 'remove_item'
root 'products#index'

get 'login' => 'sessions#new'
post 'sessions' => 'sessions#create'
delete 'logout' => 'sessions#destroy'

patch 'users/:user_id/orders/:order_id/select/:id' => 'orders#select_card', as: 'select_card'
delete 'users/:user_id/orders/:order_id/delete/:id' => 'orders#remove_card', as: 'remove_card'
post 'users/:user_id/orders/ship/:id' => 'orders#shipped', as: 'shipped_order'


  resources :users, except: [:index, :new] do
      resources :orders, :cards, except: [:index]
  end

  resources :products, only: [:index, :show]

  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Cabin' rel='stylesheet' type='text/css'>
</head>
<body>

<nav>
	<h1 id="logo"> <a href='/'>Furniture Store</a></h1>
	<ul>
		<% if current_user %>
		<li><p id="welcome">Welcome <%= link_to current_user.fname.capitalize, user_path(current_user) %>  |  <%= link_to "Log Out", logout_path, method: "delete" %></p></li>
		<% else %>
		<li><p><%= link_to "Sign In", login_path %> | <%= link_to "Sign Up", login_path %></p></li>
		<% end %>	

		<% if current_user and current_user.orders.last %>
		 <li><p id="cart"><%= link_to image_tag("shopping_cart.png"), user_order_path(current_user.id, current_user.orders.last.id) %></li> 
		<% end %> 
	</ul>	
	</nav>
<hr>

<div id="flash">
	<%= flash[:notice] if flash[:notice] %>
	<%= flash[:alert] if flash[:alert] %> 
</div>


<%= yield %>

</body>
</html>